### ISSUE TITLE
Gradle 9 deprecations

### ISSUE THREAD

**Issue by fed6297d** [kontext-e/jqassistant-gradle-plugin#15]
Doing a `./gradlew scan analyze asciidoctor --warning-mode all` I get the following warnings during scan:

```
The org.gradle.api.plugins.Convention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.10/userguide/upgrading_version_8.html#deprecated_access_to_conventions
The org.gradle.api.plugins.JavaPluginConvention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.10/userguide/upgrading_version_8.html#java_convention_deprecation
```

I can see, that at least `JavaPluginConvention ` is used in the current plugin code, so at leats some code has to be changed to be gradle 9 compatible

**Comment by WilliamThimm** [comment]
Hello @fed6297d,

Plugin version 3.0.0 no longer uses any deprecated Gradle types, making it compatible with Gradle 9.0. Note that the ID of the plugin has changed to conform with Gradle guidlines. Please have a look at the README for more information on how to use the new version.

If there are still any issues, please feel free to reach out again!
