### ISSUE TITLE
Discussion about compatible gradle versions

### ISSUE THREAD

**Issue by dhamann** [kontext-e/jqassistant-gradle-plugin#8]
Hi there,

* i personally try to use the latest gradle versions and am able to upgrade my pet projects to that version rather quickly
* my employed self has to deal with quite a range of gradle-versions that the builds had been created in and which _not_ were upgraded

as such, i  first was very interested in finding out if this plugin supports the newest gradle (currently 7.1.*) ... and when i saw that the last committed versions were running on 5.6.3 i expected some bumpy road.  As it seems #7 adresses some breaking changes.

So i currently could use jqa gradle plugin with some older work-projects configured to gradle <= 5.6.3 but nothing newer. (maybe some newer, but not 6.8.3 (#7) or 7.1.1 (https://github.com/kontext-e/jqa-gradle/issues/1#issue-941301124)

Is this plugin the most promising plugin to use jqa via gradle build? Or are there alternatives?

cheers,

**Comment by dhamann** [comment]
oh i forgot ... nudge nudge @kontext-e 😎

**Comment by f4lco** [comment]
@dhamann I'm not sure what the question is, but from the perspective of a passer-by: yep, this is the most promising plugin for using jqa directly from within Gradle. I'm currently using this plugin with Gradle 7.1.1 and it is working fine so far.
